version: '3.8'
services:
  db:
    image: postgres:17.4
    container_name: tech_blog_database
    environment:
      POSTGRES_DB: 'tech_blog'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_USER: 'root'
    ports:
      - '5432:5432'
    volumes:
      - $HOME/Dev/docker/volumes/tech_blog:/var/lib/postgresql/data
